#!/usr/bin/env julia
#
# Turn a dump of the C reference's fpr_gm_tab into test/vectors/fft_roots_c_kat.jl.
#
#     cc -O2 -o gmdump cref_gm_dump.c fpr.c        # see cref_gm_dump.c
#     ./gmdump > gm.txt
#     julia falcon/scripts/gen_fft_roots_c_kat.jl gm.txt
#
# The input is one line per table entry: "<j> <re_hex> <im_hex>", with j the
# C-side index and the two fields the raw 64-bit patterns.
#
# The output is keyed by *angle*, not by j.  C's j is a position in its FFT
# recursion; ours is a position in ours; they are not the same numbering and
# lining them up by index compares two different populations.  So each entry's
# angle is recovered from its own value -- atan2 at 200-bit precision, which
# lands on a multiple of pi/1024 to within 1e-9 -- and that is the key.  Any
# entry whose angle is *not* such a multiple is an error, not a rounding
# artefact, and this script stops rather than guessing.
#
# docs/debug_log.md #031.

setprecision(BigFloat, 200)

function main(args)
    length(args) == 1 || error("usage: gen_fft_roots_c_kat.jl <gm dump>")
    src = args[1]

    entries = Dict{Int,Tuple{UInt64,UInt64}}()
    for line in eachline(src)
        f = split(line)
        length(f) == 3 || continue
        j = parse(Int, f[1])
        j == 0 && continue                      # slot 0 is unused in C's table
        rb = parse(UInt64, f[2], base = 16)
        ib = parse(UInt64, f[3], base = 16)
        re = reinterpret(Float64, rb)
        im = reinterpret(Float64, ib)

        th = atan(big(im), big(re)) / big(pi)   # angle / pi, in (-1, 1]
        kf = Float64(th * 1024)
        k = round(Int, kf)
        abs(kf - k) < 1e-9 ||
            error("entry $j is at angle $(kf)/1024 * pi, not a multiple of pi/1024")
        k < 0 && (k += 2048)

        if haskey(entries, k) && entries[k] != (rb, ib)
            error("entry $j gives angle k=$k, which is already present with a " *
                  "different value -- C's table is not consistent, or the " *
                  "angle recovery is wrong")
        end
        entries[k] = (rb, ib)
    end

    out = joinpath(@__DIR__, "..", "test", "vectors", "fft_roots_c_kat.jl")
    open(out, "w") do io
        println(io, """
        # AUTOGENERATED from the C reference implementation -- do not edit by hand.
        # Regenerate with:  julia falcon/scripts/gen_fft_roots_c_kat.jl <gm dump>
        # Oracle: falcon_inner_fpr_gm_tab, dumped from a compiled C reference binary
        #         (scripts/cref_gm_dump.c).  The emulated-FP build (uint64 bit
        #         patterns) and the native-FP build (27-digit decimal literals) were
        #         checked against each other first: all 1024 table slots agree
        #         bit-for-bit, so there is one table here, not two.
        #
        # RE-KEYED BY ANGLE, not by C's index.  C stores entry j at slots 2j and 2j+1
        # and its j is a position in the FFT's own recursion, not a multiple of pi/1024
        # -- comparing "entry j" against "our root j" is comparing two different
        # populations, which is how the first attempt at this produced a meaningless
        # number (docs/debug_log.md #031).  So each entry's angle was recovered from
        # its own value (atan2 in high precision, which lands exactly on a multiple of
        # pi/1024) and that angle is the key here.  The C-side indexing then drops out
        # of the comparison entirely.
        #
        # GM_TAB_C[k] is exp(i*pi*k/1024) as C stores it, given as the raw IEEE-754
        # bit patterns of the two Float64 components.  Every root of x^n+1 for any
        # n <= 1024 in the tower appears here, because exp(i*pi*k/n) =
        # exp(i*pi*(k*1024/n)/1024).  Angles above pi are obtained by conjugation,
        # which is exact.  See docs/debug_log.md #031.
        const GM_TAB_C = Dict{Int,Tuple{UInt64,UInt64}}(""")
        for k in sort(collect(keys(entries)))
            re, im = entries[k]
            println(io, "    ", k, " => (0x", string(re, base = 16, pad = 16),
                    ", 0x", string(im, base = 16, pad = 16), "),")
        end
        println(io, ")")
    end
    println("wrote ", length(entries), " entries to ", out)
end

main(ARGS)
