#!/usr/bin/env python3
"""Golden-vector generator for the Julia FALCON implementation.

Runs the vendored Python reference implementation (``scripts/pyref``, MIT,
Thomas Prest) plus the Python standard library, and emits Julia source files
under ``test/vectors/`` that the Julia test suite ``include``s.

Rationale
---------
The project methodology is "cross-check every module against a reference".
The primary oracle is the C reference implementation via ``ccall``; this
generator is the *secondary* oracle.  It exists because:

  1. it needs no build step, so a broken C build never blocks a Julia test;
  2. the Python reference is written in the same idiom as the specification's
     pseudocode, so a mismatch points at a spec-reading error rather than at a
     C-level micro-optimisation;
  3. the vectors are checked into git, so the Julia tests are reproducible on
     a machine that has neither Python nor the C reference available.

Usage
-----
    python3 scripts/gen_vectors.py

Deterministic: no ``os.urandom`` anywhere.  All randomness comes from a
SHAKE256 stream keyed by a fixed domain-separation string, so re-running this
script must reproduce the files byte for byte.  (If it does not, that is
itself a bug worth an entry in docs/debug_log.md.)
"""

import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, "pyref"))

from common import q as REF_Q            # noqa: E402
from ntt import mul_zq, div_zq, add_zq, sub_zq  # noqa: E402
from rng import ChaCha20 as _RefChaCha20  # noqa: E402


class ChaCha20(_RefChaCha20):
    """The reference PRNG with a *64-bit* block counter.

    The vendored Python reference keeps its counter in a Python int, which
    never wraps.  The C reference holds it in a `uint64_t` (`rng.c`,
    `prng_refill`: `cc = *(uint64_t *)(p->state.d + 48); ... cc + 8`), so it
    wraps modulo 2**64.  The two agree until the counter overflows, which a
    seed of all-0xff bytes does immediately -- and then the Python version
    starts XORing a 33-bit value into a 32-bit state word and diverges.

    The C reference is normative, so we mask.  See docs/debug_log.md #016.
    """

    def update(self):
        self.ctr &= (1 << 64) - 1
        return super().update()

OUT = os.path.join(ROOT, "test", "vectors")

BANNER = """# AUTOGENERATED by scripts/gen_vectors.py -- do not edit by hand.
# Oracle: Python reference implementation (scripts/pyref, MIT, Thomas Prest)
#         + CPython hashlib (SHAKE256, FIPS 202).
# Regenerate with:  python3 scripts/gen_vectors.py
"""


# ---------------------------------------------------------------------------
# deterministic pseudo-randomness for the test inputs themselves
# ---------------------------------------------------------------------------

def stream(label, nbytes):
    """Deterministic byte stream, domain-separated by `label`."""
    return hashlib.shake_256(b"falcon-jl/vectors/" + label.encode()).digest(nbytes)


def rand_poly(label, n, bound):
    """A deterministic length-n integer polynomial with coefficients in [0,bound)."""
    raw = stream(label, 4 * n)
    return [int.from_bytes(raw[4 * i:4 * i + 4], "little") % bound for i in range(n)]


def rand_signed_poly(label, n, half):
    """Coefficients in [-half, half]; models the small f, g of key generation."""
    return [c - half for c in rand_poly(label, n, 2 * half + 1)]


# ---------------------------------------------------------------------------
# Julia literal emission
# ---------------------------------------------------------------------------

def jl_intvec(v):
    return "[" + ", ".join(str(int(x)) for x in v) + "]"


def jl_bytes(b):
    return "UInt8[" + ", ".join("0x%02x" % x for x in b) + "]"


def write(name, body):
    path = os.path.join(OUT, name)
    with open(path, "w") as fh:
        fh.write(BANNER + "\n" + body)
    print("wrote %s (%d bytes)" % (os.path.relpath(path, ROOT), os.path.getsize(path)))


# ---------------------------------------------------------------------------
# module 2: SHAKE256 / ChaCha20
# ---------------------------------------------------------------------------

def gen_shake():
    lines = ["# (input bytes, requested output length, expected output bytes)",
             "const SHAKE256_KAT = Tuple{Vector{UInt8},Int,Vector{UInt8}}[",
             ]
    cases = [
        (b"", 32),
        (b"", 200),
        (b"abc", 64),
        (b"The quick brown fox jumps over the lazy dog", 32),
        (bytes(range(256)), 137),          # multi-block absorb
        (bytes(200), 1),                   # exactly one block of zeros in, 1 byte out
        (bytes(135), 512),                 # blocklen-1 absorb: exercises the padding branch
        (bytes(136), 512),                 # exactly blocklen: exercises the extra-block branch
        (bytes(137), 64),                  # blocklen+1
    ]
    for msg, dlen in cases:
        out = hashlib.shake_256(msg).digest(dlen)
        lines.append("    (%s, %d, %s)," % (jl_bytes(msg), dlen, jl_bytes(out)))
    lines.append("]\n")

    # The prefix property: SHAKE256(m, d1) must be a prefix of SHAKE256(m, d2)
    # for d1 < d2.  This was load-bearing when the module was built on
    # SHA.shake256; now that we implement the sponge ourselves it is a property
    # of our own incremental squeeze, which is exactly as worth testing.
    lines.append("# prefix property: (input, short length, long length, expected long output)")
    lines.append("const SHAKE256_PREFIX = Tuple{Vector{UInt8},Int,Int,Vector{UInt8}}[")
    for msg, d1, d2 in [(b"", 8, 300), (b"falcon", 31, 32), (b"falcon", 136, 137),
                        (b"falcon", 1, 1000)]:
        lines.append("    (%s, %d, %d, %s)," %
                     (jl_bytes(msg), d1, d2, jl_bytes(hashlib.shake_256(msg).digest(d2))))
    lines.append("]\n")
    write("shake256_kat.jl", "\n".join(lines))


def gen_chacha():
    lines = ["# ChaCha20-based PRNG of the FALCON reference implementation.",
             "# Oracle: scripts/pyref/rng.py (a transliteration of the C reference PRNG).",
             "# Each case: (56-byte seed, list of successive randombytes() request sizes,",
             "#             list of the corresponding outputs)",
             "const CHACHA20_KAT = Tuple{Vector{UInt8},Vector{Int},Vector{Vector{UInt8}}}[",
             ]
    seeds = [
        bytes(range(56)),
        bytes(56),
        stream("chacha-seed-3", 56),
        b"\xff" * 56,
    ]
    # Request patterns chosen to straddle the 512-byte block boundary, because
    # randombytes() *discards* the unused tail of the buffer when a request
    # does not fit -- an easy behaviour to get wrong when reimplementing.
    patterns = [
        [16, 16, 16],
        [1, 2, 3, 4, 5],
        [255, 255, 255],       # 3rd request forces a refill mid-stream
        [512],                 # exactly the buffer size
        [511, 8],              # 8-byte request after 511 consumed -> refill + discard
    ]
    for seed in seeds:
        for pat in patterns:
            rng = ChaCha20(seed)
            outs = [rng.randombytes(k) for k in pat]
            lines.append("    (%s, %s, [%s])," % (
                jl_bytes(seed), jl_intvec(pat),
                ", ".join(jl_bytes(o) for o in outs)))
    lines.append("]\n")
    write("chacha20_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 3: polynomial arithmetic in R = Z[x]/(x^n + 1)
# ---------------------------------------------------------------------------

def negacyclic_mul_Z(f, g):
    """Reference negacyclic product over *Z* (no modular reduction).

    Deliberately the most naive possible O(n^2) implementation: this is the
    definition, and it is what the Julia side must reproduce.  Computed with
    Python ints, i.e. exact arbitrary precision, so that it also serves as the
    oracle for the places where the Julia code needs Int128/BigInt.
    """
    n = len(f)
    assert len(g) == n
    out = [0] * n
    for i in range(n):
        for j in range(n):
            k = i + j
            if k < n:
                out[k] += f[i] * g[j]
            else:
                out[k - n] -= f[i] * g[j]      # x^n = -1
    return out


def gen_poly():
    lines = []
    lines.append("const POLY_Q = %d\n" % REF_Q)

    # --- negacyclic multiplication over the integers -----------------------
    lines.append("# (f, g, f*g in Z[x]/(x^n+1)) with *no* modular reduction.")
    lines.append("# Oracle: naive O(n^2) definition evaluated with Python bigints.")
    lines.append("const NEGACYCLIC_Z = Tuple{Vector{BigInt},Vector{BigInt},Vector{BigInt}}[")
    for n, half, label in [(2, 3, "z2"), (4, 5, "z4"), (8, 7, "z8"),
                           (16, 100, "z16"), (32, 1000, "z32")]:
        f = rand_signed_poly(label + "f", n, half)
        g = rand_signed_poly(label + "g", n, half)
        lines.append("    (%s, %s, %s)," %
                     (jl_intvec(f), jl_intvec(g), jl_intvec(negacyclic_mul_Z(f, g))))
    # A case with deliberately large coefficients: the product must overflow
    # Int64, which is exactly the trap that bites in ntrugen.jl.
    #
    # The first version of this fixture used a bound of 1e9 and did NOT
    # overflow: random signs cancel, so the largest product coefficient came
    # out at 5.8e18, just under typemax(Int64) = 9.2e18.  The test asserting
    # that Int64 raises therefore failed against correct code.  Hence the
    # bigger bound *and* the assertion below, so the fixture cannot quietly
    # weaken again.  See docs/debug_log.md #017.
    big = 10 ** 10
    f = rand_signed_poly("zbigf", 64, big)
    g = rand_signed_poly("zbigg", 64, big)
    assert max(abs(c) for c in negacyclic_mul_Z(f, g)) > 2 ** 63 - 1, \
        "the overflow fixture must actually overflow Int64"
    lines.append("    (%s, %s, %s)," %
                 (jl_intvec(f), jl_intvec(g), jl_intvec(negacyclic_mul_Z(f, g))))
    lines.append("]\n")

    # --- arithmetic modulo q ----------------------------------------------
    # Oracle here is the reference's NTT-based mul_zq, which is an *independent*
    # algorithm from our naive convolution.  Agreement is therefore meaningful.
    lines.append("# (f, g, f+g, f-g, f*g) all mod q, coefficients in [0, q).")
    lines.append("# Oracle: scripts/pyref/ntt.py (NTT-based), independent of the naive")
    lines.append("# schoolbook convolution the Julia side computes.")
    lines.append("const NEGACYCLIC_ZQ = " +
                 "Tuple{Vector{Int},Vector{Int},Vector{Int},Vector{Int},Vector{Int}}[")
    for n, label in [(2, "q2"), (4, "q4"), (8, "q8"), (16, "q16"),
                     (64, "q64"), (512, "q512"), (1024, "q1024")]:
        f = rand_poly(label + "f", n, REF_Q)
        g = rand_poly(label + "g", n, REF_Q)
        lines.append("    (%s, %s, %s, %s, %s)," % (
            jl_intvec(f), jl_intvec(g),
            jl_intvec(add_zq(f, g)), jl_intvec(sub_zq(f, g)), jl_intvec(mul_zq(f, g))))
    lines.append("]\n")

    # --- division mod q ----------------------------------------------------
    # div_zq returns None when the divisor is not invertible; we only keep the
    # invertible cases here and test non-invertibility separately.
    lines.append("# (f, g, f/g mod q) for invertible g.")
    lines.append("const DIV_ZQ = Tuple{Vector{Int},Vector{Int},Vector{Int}}[")
    kept = 0
    idx = 0
    while kept < 4:
        idx += 1
        n = [4, 8, 16, 512][kept]
        f = rand_poly("dvf%d" % idx, n, REF_Q)
        g = rand_poly("dvg%d" % idx, n, REF_Q)
        try:
            h = div_zq(f, g)
        except ZeroDivisionError:
            continue
        if h is None:
            continue
        lines.append("    (%s, %s, %s)," % (jl_intvec(f), jl_intvec(g), jl_intvec(h)))
        kept += 1
    lines.append("]\n")

    # --- adjoint / Galois conjugate ---------------------------------------
    # adj(f)(x) = f(1/x) = f(x^-1); in R = Z[x]/(x^n+1) this is
    # adj(f)_0 = f_0 and adj(f)_i = -f_{n-i}.  It is the map that turns
    # <f*a, b> into <a, adj(f)*b>, i.e. the Hermitian adjoint of
    # multiplication-by-f, which is why LDL* needs it.
    lines.append("# (f, adj(f)) over Z, adj(f)_0 = f_0, adj(f)_i = -f_{n-i}.")
    lines.append("const ADJ_Z = Tuple{Vector{BigInt},Vector{BigInt}}[")
    for n, label in [(2, "a2"), (4, "a4"), (8, "a8"), (16, "a16")]:
        f = rand_signed_poly(label, n, 50)
        adj = [f[0]] + [-f[n - i] for i in range(1, n)]
        lines.append("    (%s, %s)," % (jl_intvec(f), jl_intvec(adj)))
    lines.append("]\n")

    write("poly_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 4: the NTT over Z_q
# ---------------------------------------------------------------------------

def gen_ntt():
    from ntt import ntt, intt, mul_ntt, div_ntt          # noqa: E402
    from ntt_constants import roots_dict_Zq              # noqa: E402

    lines = []

    # The root tables.  Our Julia implementation *generates* these from a
    # primitive 2048-th root of unity rather than hard-coding 2046 numbers, so
    # these vectors are what certifies that the generation reproduces the
    # reference's ordering exactly -- and the ordering is not incidental, it is
    # what makes split_ntt/merge_ntt line up with the FFT tree.
    lines.append("# roots_dict_Zq[n] = the n roots of x^n + 1 mod q, in the")
    lines.append("# reference's recursive order.  Oracle: scripts/pyref/ntt_constants.py")
    lines.append("const ROOTS_ZQ = Dict{Int,Vector{Int}}(")
    for n in sorted(roots_dict_Zq):
        lines.append("    %d => %s," % (n, jl_intvec(roots_dict_Zq[n])))
    lines.append(")\n")

    # (f, ntt(f)) pairs.
    lines.append("# (f, ntt(f)); the NTT is multipoint evaluation at ROOTS_ZQ[n].")
    lines.append("const NTT_KAT = Tuple{Vector{Int},Vector{Int}}[")
    for n, label in [(2, "n2"), (4, "n4"), (8, "n8"), (16, "n16"),
                     (64, "n64"), (512, "n512"), (1024, "n1024")]:
        f = rand_poly("ntt" + label, n, REF_Q)
        lines.append("    (%s, %s)," % (jl_intvec(f), jl_intvec(ntt(f))))
    # edge cases worth pinning: the constant polynomial and a monomial
    for n in (8, 512):
        one = [1] + [0] * (n - 1)
        lines.append("    (%s, %s)," % (jl_intvec(one), jl_intvec(ntt(one))))
        xx = [0, 1] + [0] * (n - 2)
        lines.append("    (%s, %s)," % (jl_intvec(xx), jl_intvec(ntt(xx))))
    lines.append("]\n")

    # Pointwise operations in the NTT domain.
    lines.append("# (f_ntt, g_ntt, f*g pointwise, f/g pointwise) for invertible g_ntt.")
    lines.append("const NTT_POINTWISE = " +
                 "Tuple{Vector{Int},Vector{Int},Vector{Int},Vector{Int}}[")
    for n, label in [(8, "p8"), (64, "p64"), (512, "p512")]:
        fn = ntt(rand_poly("pw" + label + "f", n, REF_Q))
        gn = ntt(rand_poly("pw" + label + "g", n, REF_Q))
        if any(x == 0 for x in gn):
            continue
        lines.append("    (%s, %s, %s, %s)," % (
            jl_intvec(fn), jl_intvec(gn),
            jl_intvec(mul_ntt(fn, gn)), jl_intvec(div_ntt(fn, gn))))
    lines.append("]\n")

    # A polynomial that is *not* invertible mod q, i.e. has a zero NTT
    # coefficient.  Key generation must reject such an f (falcon.py rejects it
    # via `if any((elem == 0) for elem in f_ntt)`), so we need a witness.
    lines.append("# f with a zero NTT coefficient: key generation must reject these.")
    lines.append("const NOT_INVERTIBLE = Tuple{Vector{Int},Int}[")
    for n, label in [(8, "ni8"), (64, "ni64"), (512, "ni512")]:
        g = ntt(rand_poly("ni" + label, n, REF_Q))
        zero_at = (7 * n) // 13 % n            # arbitrary but deterministic
        g[zero_at] = 0
        f = intt(g)
        assert any(x == 0 for x in ntt(f))
        lines.append("    (%s, %d)," % (jl_intvec(f), zero_at))
    lines.append("]\n")

    write("ntt_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 5: the FFT over C
# ---------------------------------------------------------------------------

def jl_floatvec(v):
    return "[" + ", ".join(repr(float(x)) for x in v) + "]"


def jl_cplxvec(v):
    return ("ComplexF64[" +
            ", ".join("complex(%r, %r)" % (float(z.real), float(z.imag)) for z in v) +
            "]")


def gen_fft():
    from fft import fft, ifft, mul_fft, div_fft, adj_fft   # noqa: E402
    from fft_constants import roots_dict                   # noqa: E402

    lines = []
    lines.append("# NOTE ON TOLERANCE: the Python reference's hard-coded root table carries")
    lines.append("# decimal constants of only ~15 significant digits -- up to about 370 ulp")
    lines.append("# of error at n = 512.  Our Julia implementation computes its roots with")
    lines.append("# cispi and is *more* accurate, so these vectors must be compared with a")
    lines.append("# tolerance, not for equality.  The tight comparison lives in")
    lines.append("# fft_c_kat.jl, whose oracle is the correctly-rounded C table.")
    lines.append("")

    lines.append("# roots_dict[n]: the n roots of x^n+1 in C, in the reference's order.")
    lines.append("const ROOTS_C = Dict{Int,Vector{ComplexF64}}(")
    for n in sorted(roots_dict):
        lines.append("    %d => %s," % (n, jl_cplxvec(roots_dict[n])))
    lines.append(")\n")

    lines.append("# (f, fft(f))")
    lines.append("const FFT_KAT = Tuple{Vector{Float64},Vector{ComplexF64}}[")
    cases = []
    for n, label, bound in [(2, "s2", 10), (4, "s4", 10), (8, "s8", 10),
                            (16, "s16", 10), (64, "s64", 100),
                            (512, "s512", 100), (1024, "s1024", 100)]:
        f = [float(c) for c in rand_signed_poly("fft" + label, n, bound)]
        cases.append(f)
        lines.append("    (%s, %s)," % (jl_floatvec(f), jl_cplxvec(fft(f))))
    lines.append("]\n")

    # Products and adjoints, to pin the FFT-domain operations.
    lines.append("# (f, g, f*g via FFT, f/g via FFT, adj(f) via FFT) in the coefficient domain")
    lines.append("const FFT_OPS = " +
                 "Tuple{Vector{Float64},Vector{Float64},Vector{Float64}," +
                 "Vector{Float64},Vector{Float64}}[")
    for n, label in [(8, "o8"), (64, "o64"), (512, "o512")]:
        f = [float(c) for c in rand_signed_poly("fo" + label + "f", n, 20)]
        g = [float(c) for c in rand_signed_poly("fo" + label + "g", n, 20)]
        # keep g away from a near-zero spectrum so the division is well conditioned
        g[0] += 1000.0
        lines.append("    (%s, %s, %s, %s, %s)," % (
            jl_floatvec(f), jl_floatvec(g),
            jl_floatvec(ifft(mul_fft(fft(f), fft(g)))),
            jl_floatvec(ifft(div_fft(fft(f), fft(g)))),
            jl_floatvec(ifft(adj_fft(fft(f))))))
    lines.append("]\n")

    write("fft_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 6: solving the NTRU equation
# ---------------------------------------------------------------------------

def gen_ntrugen():
    from ntrugen import (ntru_solve, field_norm, galois_conjugate, lift,
                         karamul, bitsize, gs_norm)          # noqa: E402

    lines = []

    # --- the tower operations, on small inputs that can be checked by hand ---
    lines.append("# (a, galois_conjugate(a) = a(-x), field_norm(a), lift(a))")
    lines.append("const TOWER_OPS = " +
                 "Tuple{Vector{BigInt},Vector{BigInt},Vector{BigInt},Vector{BigInt}}[")
    for n, label, bound in [(2, "t2", 5), (4, "t4", 5), (8, "t8", 10),
                            (16, "t16", 20), (64, "t64", 30)]:
        a = rand_signed_poly("tow" + label, n, bound)
        lines.append("    (%s, %s, %s, %s)," % (
            jl_intvec(a), jl_intvec(galois_conjugate(a)),
            jl_intvec(field_norm(a)), jl_intvec(lift(a))))
    lines.append("]\n")

    # --- bitsize: rounded up to a multiple of 8, sign ignored ---
    lines.append("# (a, bitsize(a)); note bitsize is rounded UP to a multiple of 8")
    lines.append("const BITSIZE_KAT = Tuple{BigInt,Int}[")
    vals = [0, 1, -1, 127, 128, 255, 256, -256, 2 ** 53, -(2 ** 53),
            2 ** 100 + 7, -(2 ** 100 + 7), 2 ** 1000]
    for v in vals:
        lines.append("    (%d, %d)," % (v, bitsize(v)))
    lines.append("]\n")

    # --- full solutions ---
    # Finding a solvable (f, g) is itself part of key generation: the descent
    # fails when the bottom-level gcd is not 1, and the reference resamples.
    # We record the number of attempts so the Julia test can assert that the
    # *same* attempt succeeds, which pins the failure path too.
    lines.append("# (f, g, F, G, attempts) with f*G - g*F = q exactly.")
    lines.append("# `attempts` is how many (f, g) draws from the labelled stream were")
    lines.append("# rejected with NTRUSolveFailure before this one worked.")
    lines.append("const NTRU_SOLVE_KAT = " +
                 "Tuple{Vector{BigInt},Vector{BigInt},Vector{BigInt},Vector{BigInt},Int}[")
    rejected = []
    for n, bound in [(2, 5), (4, 5), (8, 6), (16, 6), (32, 6), (64, 6), (128, 6)]:
        attempt = 0
        while True:
            f = rand_signed_poly("nsf%d_%d" % (n, attempt), n, bound)
            g = rand_signed_poly("nsg%d_%d" % (n, attempt), n, bound)
            try:
                F, G = ntru_solve(f, g)
            except (ValueError, ZeroDivisionError):
                rejected.append((f, g))
                attempt += 1
                if attempt > 200:
                    raise RuntimeError("no solvable (f,g) found at n=%d" % n)
                continue
            break
        # verify exactly before writing it down
        r = [x - y for x, y in zip(karamul(f, G), karamul(g, F))]
        assert r[0] == REF_Q and all(c == 0 for c in r[1:]), \
            "generator produced a bad NTRU solution at n=%d" % n
        lines.append("    (%s, %s, %s, %s, %d)," % (
            jl_intvec(f), jl_intvec(g), jl_intvec(F), jl_intvec(G), attempt))
        print("  n=%4d solved after %d rejected draw(s)" % (n, attempt))
    lines.append("]\n")

    # --- an (f, g) for which the descent genuinely fails ---
    lines.append("# (f, g) pairs whose descent hits gcd != 1: ntru_solve must throw.")
    lines.append("# These are not contrived -- they are simply the draws that key")
    lines.append("# generation would reject and resample.")
    lines.append("const NTRU_SOLVE_FAILS = Tuple{Vector{BigInt},Vector{BigInt}}[")
    for n, bound in [(2, 5), (4, 5), (8, 6)]:
        for k in range(500):
            f = rand_signed_poly("nff%d_%d" % (n, k), n, bound)
            g = rand_signed_poly("nfg%d_%d" % (n, k), n, bound)
            try:
                ntru_solve(f, g)
            except (ValueError, ZeroDivisionError):
                lines.append("    (%s, %s)," % (jl_intvec(f), jl_intvec(g)))
                break
        else:
            raise RuntimeError("no failing (f,g) found at n=%d" % n)
    # plus every draw that the loop above actually rejected -- these are real
    # rejections from the real generation path, not hunted-for ones.
    for f, g in rejected:
        lines.append("    (%s, %s)," % (jl_intvec(f), jl_intvec(g)))
    lines.append("]\n")
    print("  recorded %d rejected draw(s) as failure cases" % len(rejected))

    # --- candidate draws at the target dimensions -------------------------
    # No expected output: the NTRU equation is self-validating, so the Julia
    # test solves these itself and checks f*G - g*F = q exactly.  That gets us
    # coverage at n = 256 and 512 without waiting for the Python reference,
    # which takes minutes there.
    lines.append("# Candidate (f, g) draws at the target dimensions, with NO expected")
    lines.append("# output.  The test takes the first draw that does not raise and")
    lines.append("# verifies the equation exactly -- no oracle needed.")
    lines.append("const NTRU_SOLVE_CANDIDATES = Tuple{Int,Vector{Vector{BigInt}},Vector{Vector{BigInt}}}[")
    for n in (256, 512):
        fs = [rand_signed_poly("cand_f%d_%d" % (n, k), n, 5) for k in range(6)]
        gs = [rand_signed_poly("cand_g%d_%d" % (n, k), n, 5) for k in range(6)]
        lines.append("    (%d, [%s], [%s])," % (
            n,
            ", ".join(jl_intvec(x) for x in fs),
            ", ".join(jl_intvec(x) for x in gs)))
    lines.append("]\n")

    # --- gs_norm ---
    lines.append("# (f, g, gs_norm(f, g)) -- floating point, compare with a tolerance.")
    lines.append("const GS_NORM_KAT = Tuple{Vector{Float64},Vector{Float64},Float64}[")
    for n, bound in [(8, 6), (64, 6), (512, 6)]:
        f = rand_signed_poly("gsf%d" % n, n, bound)
        g = rand_signed_poly("gsg%d" % n, n, bound)
        lines.append("    (%s, %s, %r)," % (
            jl_floatvec([float(c) for c in f]),
            jl_floatvec([float(c) for c in g]),
            float(gs_norm(f, g, REF_Q))))
    lines.append("]\n")

    write("ntrugen_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 7: the discrete Gaussian sampler
# ---------------------------------------------------------------------------

def gen_samplerz():
    sys.path.insert(0, os.path.join(HERE, "pyref", "scripts"))
    from samplerz_KAT512 import sampler_KAT512      # noqa: E402
    from samplerz_KAT1024 import sampler_KAT1024    # noqa: E402
    from samplerz import basesampler, approxexp, RCDT, C  # noqa: E402

    lines = []
    lines.append("# The official samplerz Known Answer Tests.")
    lines.append("# Source: tprest/falcon.py, scripts/samplerz_KAT512.py and")
    lines.append("#         scripts/samplerz_KAT1024.py (MIT, Thomas Prest).")
    lines.append("#")
    lines.append("# REPLAY CONVENTION: the reference harness (test.py, KAT_randbytes)")
    lines.append("# hands the sampler the next k bytes **reversed**:")
    lines.append("#     bytes.fromhex(octets[:2k])[::-1]")
    lines.append("# so these must be replayed with ReplayBytes(...; reversed_chunks=true).")
    lines.append("# Feeding them in natural order silently produces a different sample.")
    lines.append("# See docs/debug_log.md #022.")
    lines.append("")
    lines.append("# (mu, sigma, sigmin, random octets, expected z)")
    lines.append("const SAMPLERZ_KAT = Tuple{Float64,Float64,Float64,Vector{UInt8},Int}[")
    for D in sampler_KAT512 + sampler_KAT1024:
        lines.append("    (%r, %r, %r, %s, %d)," % (
            D["mu"], D["sigma"], D["sigmin"],
            jl_bytes(bytes.fromhex(D["octets"])), D["z"]))
    lines.append("]\n")

    # basesampler in isolation: 9 bytes in, one small integer out.
    lines.append("# (9 input bytes, z0) for basesampler, fed in natural order.")
    lines.append("const BASESAMPLER_KAT = Tuple{Vector{UInt8},Int}[")
    for k in range(64):
        raw = stream("basesampler-%d" % k, 9)
        pos = [0]

        def rb(n, _raw=raw, _pos=pos):
            out = _raw[_pos[0]:_pos[0] + n]
            _pos[0] += n
            return out

        lines.append("    (%s, %d)," % (jl_bytes(raw), basesampler(randombytes=rb)))
    # the extremes: u = 0 must give the largest z0, u = all-ones the smallest
    for raw in (b"\x00" * 9, b"\xff" * 9):
        pos = [0]

        def rb(n, _raw=raw, _pos=pos):
            out = _raw[_pos[0]:_pos[0] + n]
            _pos[0] += n
            return out

        lines.append("    (%s, %d)," % (jl_bytes(raw), basesampler(randombytes=rb)))
    lines.append("]\n")

    # approxexp in isolation: this is the fixed-point core, and the place where
    # Python's unbounded ints hide the required widths.
    lines.append("# (x, ccs, approxexp(x, ccs)) -- fixed point, must match exactly.")
    lines.append("const APPROXEXP_KAT = Tuple{Float64,Float64,UInt64}[")
    import math
    xs = [0.0, 1e-9, 0.1, 0.25, 0.5, 0.6931471, 0.69314718055]
    ccss = [0.5, 0.7499908532676649, 0.9, 0.999999]
    for x in xs:
        for ccs in ccss:
            lines.append("    (%r, %r, 0x%016x)," % (x, ccs, approxexp(x, ccs)))
    lines.append("]\n")

    # the constant tables, so a transposed digit is caught immediately
    lines.append("const RCDT_REF = UInt128[" + ", ".join(str(v) for v in RCDT) + "]\n")
    lines.append("const EXP_COEFFS_REF = UInt64[" +
                 ", ".join("0x%016x" % v for v in C) + "]\n")

    write("samplerz_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 6b: key generation (needs module 7's sampler, so it comes last)
# ---------------------------------------------------------------------------

def gen_keygen():
    import ntrugen                                   # noqa: E402
    from ntrugen import gs_norm, karamul             # noqa: E402

    lines = []
    lines.append("# Key generation.  The random stream is derived from a short label so")
    lines.append("# that it need not be embedded: both sides compute")
    lines.append("#     shake256(codeunits(label), nbytes)")
    lines.append("# and our SHAKE256 is already checked against hashlib (module 2).")
    lines.append("#")
    lines.append("# gen_poly draws 4096 samples regardless of n and folds them in blocks")
    lines.append("# of 4096/n; the byte counts below pin that, since drawing n samples")
    lines.append("# directly would give the same distribution and a different stream.")
    lines.append("")

    orig = ntrugen.samplerz

    def patched_stream(label, nbytes):
        # NOTE: the emitted label is the FULL seed string, prefix included, so
        # the Julia side derives the stream from exactly what it is given and
        # cannot get the domain separation subtly wrong.
        raw = hashlib.shake_256(label.encode()).digest(nbytes)
        pos = [0]

        def rb(k):
            out = raw[pos[0]:pos[0] + k]
            if len(out) != k:
                raise IndexError("probe stream exhausted")
            pos[0] += k
            return out

        return rb, pos

    lines.append("# (n, stream label, bytes consumed, f)")
    lines.append("const GEN_POLY_KAT = Tuple{Int,String,Int,Vector{BigInt}}[")
    for n in (8, 16, 64, 512, 1024):
        label = "falcon-jl/keygen/genpoly-%d" % n
        rb, pos = patched_stream(label, 2_000_000)
        ntrugen.samplerz = lambda mu, s, smin, _rb=rb: orig(mu, s, smin, randombytes=_rb)
        f = ntrugen.gen_poly(n)
        lines.append('    (%d, "%s", %d, %s),' % (n, label, pos[0], jl_intvec(f)))
        print("  gen_poly n=%4d consumed %d bytes" % (n, pos[0]))
    lines.append("]\n")

    lines.append("# (n, stream label, bytes consumed, f, g, F, G) -- full key generation.")
    lines.append("# Only small n: the Python reference's ntru_solve is minutes at n=512,")
    lines.append("# and the NTRU equation is self-validating anyway, so the Julia test")
    lines.append("# runs the target dimension itself without an oracle.")
    lines.append("const NTRU_GEN_KAT = " +
                 "Tuple{Int,String,Int,Vector{BigInt},Vector{BigInt},Vector{BigInt},Vector{BigInt}}[")
    for n in (8, 16, 32):
        label = "falcon-jl/keygen/ntrugen-%d" % n
        rb, pos = patched_stream(label, 8_000_000)
        ntrugen.samplerz = lambda mu, s, smin, _rb=rb: orig(mu, s, smin, randombytes=_rb)
        f, g, F, G = ntrugen.ntru_gen(n)
        r = [x - y for x, y in zip(karamul(f, G), karamul(g, F))]
        assert r[0] == REF_Q and all(c == 0 for c in r[1:]), "bad key at n=%d" % n
        lines.append('    (%d, "%s", %d, %s, %s, %s, %s),' % (
            n, label, pos[0],
            jl_intvec(f), jl_intvec(g), jl_intvec(F), jl_intvec(G)))
        print("  ntru_gen n=%4d consumed %d bytes" % (n, pos[0]))
    lines.append("]\n")

    ntrugen.samplerz = orig
    write("keygen_kat.jl", "\n".join(lines))


def main():
    os.makedirs(OUT, exist_ok=True)
    gen_shake()
    gen_chacha()
    gen_poly()
    gen_ntt()
    gen_fft()
    gen_ntrugen()
    gen_samplerz()
    gen_keygen()


if __name__ == "__main__":
    main()
