#!/usr/bin/env python3
"""Golden-vector generator for the Julia FALCON implementation.

Runs the vendored Python reference implementation (``scripts/pyref``, MIT,
Thomas Prest) plus the Python standard library, and emits Julia source files
under ``test/vectors/`` that the Julia test suite ``include``s.

Rationale
---------
The project methodology is "cross-check every module against a reference".
The primary oracle is the C reference implementation via ``ccall``; this
generator is the *secondary* oracle.  It exists because:

  1. it needs no build step, so a broken C build never blocks a Julia test;
  2. the Python reference is written in the same idiom as the specification's
     pseudocode, so a mismatch points at a spec-reading error rather than at a
     C-level micro-optimisation;
  3. the vectors are checked into git, so the Julia tests are reproducible on
     a machine that has neither Python nor the C reference available.

Usage
-----
    python3 scripts/gen_vectors.py

Deterministic: no ``os.urandom`` anywhere.  All randomness comes from a
SHAKE256 stream keyed by a fixed domain-separation string, so re-running this
script must reproduce the files byte for byte.  (If it does not, that is
itself a bug worth an entry in docs/debug_log.md.)
"""

import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, "pyref"))

from common import q as REF_Q            # noqa: E402
from ntt import mul_zq, div_zq, add_zq, sub_zq  # noqa: E402
from rng import ChaCha20                 # noqa: E402

OUT = os.path.join(ROOT, "test", "vectors")

BANNER = """# AUTOGENERATED by scripts/gen_vectors.py -- do not edit by hand.
# Oracle: Python reference implementation (scripts/pyref, MIT, Thomas Prest)
#         + CPython hashlib (SHAKE256, FIPS 202).
# Regenerate with:  python3 scripts/gen_vectors.py
"""


# ---------------------------------------------------------------------------
# deterministic pseudo-randomness for the test inputs themselves
# ---------------------------------------------------------------------------

def stream(label, nbytes):
    """Deterministic byte stream, domain-separated by `label`."""
    return hashlib.shake_256(b"falcon-jl/vectors/" + label.encode()).digest(nbytes)


def rand_poly(label, n, bound):
    """A deterministic length-n integer polynomial with coefficients in [0,bound)."""
    raw = stream(label, 4 * n)
    return [int.from_bytes(raw[4 * i:4 * i + 4], "little") % bound for i in range(n)]


def rand_signed_poly(label, n, half):
    """Coefficients in [-half, half]; models the small f, g of key generation."""
    return [c - half for c in rand_poly(label, n, 2 * half + 1)]


# ---------------------------------------------------------------------------
# Julia literal emission
# ---------------------------------------------------------------------------

def jl_intvec(v):
    return "[" + ", ".join(str(int(x)) for x in v) + "]"


def jl_bytes(b):
    return "UInt8[" + ", ".join("0x%02x" % x for x in b) + "]"


def write(name, body):
    path = os.path.join(OUT, name)
    with open(path, "w") as fh:
        fh.write(BANNER + "\n" + body)
    print("wrote %s (%d bytes)" % (os.path.relpath(path, ROOT), os.path.getsize(path)))


# ---------------------------------------------------------------------------
# module 2: SHAKE256 / ChaCha20
# ---------------------------------------------------------------------------

def gen_shake():
    lines = ["# (input bytes, requested output length, expected output bytes)",
             "const SHAKE256_KAT = Tuple{Vector{UInt8},Int,Vector{UInt8}}[",
             ]
    cases = [
        (b"", 32),
        (b"", 200),
        (b"abc", 64),
        (b"The quick brown fox jumps over the lazy dog", 32),
        (bytes(range(256)), 137),          # multi-block absorb
        (bytes(200), 1),                   # exactly one block of zeros in, 1 byte out
        (bytes(135), 512),                 # blocklen-1 absorb: exercises the padding branch
        (bytes(136), 512),                 # exactly blocklen: exercises the extra-block branch
        (bytes(137), 64),                  # blocklen+1
    ]
    for msg, dlen in cases:
        out = hashlib.shake_256(msg).digest(dlen)
        lines.append("    (%s, %d, %s)," % (jl_bytes(msg), dlen, jl_bytes(out)))
    lines.append("]\n")

    # The prefix property is what our incremental-squeeze wrapper is built on:
    # SHAKE256(m, d1) must be a prefix of SHAKE256(m, d2) for d1 < d2.
    # SHA.jl re-pads on every digest! call, so we verify this explicitly rather
    # than assume it.
    lines.append("# prefix property: (input, short length, long length, expected long output)")
    lines.append("const SHAKE256_PREFIX = Tuple{Vector{UInt8},Int,Int,Vector{UInt8}}[")
    for msg, d1, d2 in [(b"", 8, 300), (b"falcon", 31, 32), (b"falcon", 136, 137),
                        (b"falcon", 1, 1000)]:
        lines.append("    (%s, %d, %d, %s)," %
                     (jl_bytes(msg), d1, d2, jl_bytes(hashlib.shake_256(msg).digest(d2))))
    lines.append("]\n")
    write("shake256_kat.jl", "\n".join(lines))


def gen_chacha():
    lines = ["# ChaCha20-based PRNG of the FALCON reference implementation.",
             "# Oracle: scripts/pyref/rng.py (a transliteration of the C reference PRNG).",
             "# Each case: (56-byte seed, list of successive randombytes() request sizes,",
             "#             list of the corresponding outputs)",
             "const CHACHA20_KAT = Tuple{Vector{UInt8},Vector{Int},Vector{Vector{UInt8}}}[",
             ]
    seeds = [
        bytes(range(56)),
        bytes(56),
        stream("chacha-seed-3", 56),
        b"\xff" * 56,
    ]
    # Request patterns chosen to straddle the 512-byte block boundary, because
    # randombytes() *discards* the unused tail of the buffer when a request
    # does not fit -- an easy behaviour to get wrong when reimplementing.
    patterns = [
        [16, 16, 16],
        [1, 2, 3, 4, 5],
        [255, 255, 255],       # 3rd request forces a refill mid-stream
        [512],                 # exactly the buffer size
        [511, 8],              # 8-byte request after 511 consumed -> refill + discard
    ]
    for seed in seeds:
        for pat in patterns:
            rng = ChaCha20(seed)
            outs = [rng.randombytes(k) for k in pat]
            lines.append("    (%s, %s, [%s])," % (
                jl_bytes(seed), jl_intvec(pat),
                ", ".join(jl_bytes(o) for o in outs)))
    lines.append("]\n")
    write("chacha20_kat.jl", "\n".join(lines))


# ---------------------------------------------------------------------------
# module 3: polynomial arithmetic in R = Z[x]/(x^n + 1)
# ---------------------------------------------------------------------------

def negacyclic_mul_Z(f, g):
    """Reference negacyclic product over *Z* (no modular reduction).

    Deliberately the most naive possible O(n^2) implementation: this is the
    definition, and it is what the Julia side must reproduce.  Computed with
    Python ints, i.e. exact arbitrary precision, so that it also serves as the
    oracle for the places where the Julia code needs Int128/BigInt.
    """
    n = len(f)
    assert len(g) == n
    out = [0] * n
    for i in range(n):
        for j in range(n):
            k = i + j
            if k < n:
                out[k] += f[i] * g[j]
            else:
                out[k - n] -= f[i] * g[j]      # x^n = -1
    return out


def gen_poly():
    lines = []
    lines.append("const POLY_Q = %d\n" % REF_Q)

    # --- negacyclic multiplication over the integers -----------------------
    lines.append("# (f, g, f*g in Z[x]/(x^n+1)) with *no* modular reduction.")
    lines.append("# Oracle: naive O(n^2) definition evaluated with Python bigints.")
    lines.append("const NEGACYCLIC_Z = Tuple{Vector{BigInt},Vector{BigInt},Vector{BigInt}}[")
    for n, half, label in [(2, 3, "z2"), (4, 5, "z4"), (8, 7, "z8"),
                           (16, 100, "z16"), (32, 1000, "z32")]:
        f = rand_signed_poly(label + "f", n, half)
        g = rand_signed_poly(label + "g", n, half)
        lines.append("    (%s, %s, %s)," %
                     (jl_intvec(f), jl_intvec(g), jl_intvec(negacyclic_mul_Z(f, g))))
    # A case with deliberately large coefficients: the product overflows Int64
    # if you are careless, which is exactly the trap that bites in ntrugen.jl.
    big = 10 ** 9
    f = rand_signed_poly("zbigf", 64, big)
    g = rand_signed_poly("zbigg", 64, big)
    lines.append("    (%s, %s, %s)," %
                 (jl_intvec(f), jl_intvec(g), jl_intvec(negacyclic_mul_Z(f, g))))
    lines.append("]\n")

    # --- arithmetic modulo q ----------------------------------------------
    # Oracle here is the reference's NTT-based mul_zq, which is an *independent*
    # algorithm from our naive convolution.  Agreement is therefore meaningful.
    lines.append("# (f, g, f+g, f-g, f*g) all mod q, coefficients in [0, q).")
    lines.append("# Oracle: scripts/pyref/ntt.py (NTT-based), independent of the naive")
    lines.append("# schoolbook convolution the Julia side computes.")
    lines.append("const NEGACYCLIC_ZQ = " +
                 "Tuple{Vector{Int},Vector{Int},Vector{Int},Vector{Int},Vector{Int}}[")
    for n, label in [(2, "q2"), (4, "q4"), (8, "q8"), (16, "q16"),
                     (64, "q64"), (512, "q512"), (1024, "q1024")]:
        f = rand_poly(label + "f", n, REF_Q)
        g = rand_poly(label + "g", n, REF_Q)
        lines.append("    (%s, %s, %s, %s, %s)," % (
            jl_intvec(f), jl_intvec(g),
            jl_intvec(add_zq(f, g)), jl_intvec(sub_zq(f, g)), jl_intvec(mul_zq(f, g))))
    lines.append("]\n")

    # --- division mod q ----------------------------------------------------
    # div_zq returns None when the divisor is not invertible; we only keep the
    # invertible cases here and test non-invertibility separately.
    lines.append("# (f, g, f/g mod q) for invertible g.")
    lines.append("const DIV_ZQ = Tuple{Vector{Int},Vector{Int},Vector{Int}}[")
    kept = 0
    idx = 0
    while kept < 4:
        idx += 1
        n = [4, 8, 16, 512][kept]
        f = rand_poly("dvf%d" % idx, n, REF_Q)
        g = rand_poly("dvg%d" % idx, n, REF_Q)
        try:
            h = div_zq(f, g)
        except ZeroDivisionError:
            continue
        if h is None:
            continue
        lines.append("    (%s, %s, %s)," % (jl_intvec(f), jl_intvec(g), jl_intvec(h)))
        kept += 1
    lines.append("]\n")

    # --- adjoint / Galois conjugate ---------------------------------------
    # adj(f)(x) = f(1/x) = f(x^-1); in R = Z[x]/(x^n+1) this is
    # adj(f)_0 = f_0 and adj(f)_i = -f_{n-i}.  It is the map that turns
    # <f*a, b> into <a, adj(f)*b>, i.e. the Hermitian adjoint of
    # multiplication-by-f, which is why LDL* needs it.
    lines.append("# (f, adj(f)) over Z, adj(f)_0 = f_0, adj(f)_i = -f_{n-i}.")
    lines.append("const ADJ_Z = Tuple{Vector{BigInt},Vector{BigInt}}[")
    for n, label in [(2, "a2"), (4, "a4"), (8, "a8"), (16, "a16")]:
        f = rand_signed_poly(label, n, 50)
        adj = [f[0]] + [-f[n - i] for i in range(1, n)]
        lines.append("    (%s, %s)," % (jl_intvec(f), jl_intvec(adj)))
    lines.append("]\n")

    write("poly_kat.jl", "\n".join(lines))


def main():
    os.makedirs(OUT, exist_ok=True)
    gen_shake()
    gen_chacha()
    gen_poly()


if __name__ == "__main__":
    main()
