#!/usr/bin/env julia
#
# Record the C reference's signing behaviour as a Julia vector file, so the
# test suite can check byte-for-byte reproduction without a C compiler.
#
#     cd falcon/scripts/cref
#     cc -O2 -fPIC -shared -o /tmp/libfalconshim.so ../cref_shim.c \
#        codec.c common.c falcon.c fft.c fpr.c keygen.c rng.c shake.c vrfy.c -lm
#     julia --project=falcon falcon/scripts/gen_cref_sign_kat.jl /tmp/libfalconshim.so \
#         > falcon/test/vectors/cref_sign_kat.jl
#
# Each record fixes everything the signature depends on: the short basis, the
# hashed message, and the 56-byte ChaCha20 state the sampler draws from.  The
# expected values are C's, obtained through `shim_sign_tree`, which is
# `Zf(sign_tree)` with the PRNG seeded directly instead of through SHAKE.
using Falcon, Printf
const SHIM = ARGS[1]

c_expand(f, g, F, G, logn) = begin
    n = 1 << logn
    ek = zeros(Float64, (8*logn + 40) * n ÷ 8)
    ccall((:falcon_inner_expand_privkey, SHIM), Cvoid,
          (Ptr{Float64}, Ptr{Int8}, Ptr{Int8}, Ptr{Int8}, Ptr{Int8}, Cuint, Ptr{UInt8}),
          ek, Int8.(f), Int8.(g), Int8.(F), Int8.(G), logn, zeros(UInt8, 48n))
    ek
end
c_sign(st, ek, hm, logn) = begin
    n = 1 << logn; sig = zeros(Int16, n)
    ccall((:shim_sign_tree, SHIM), Cint,
          (Ptr{Int16}, Ptr{UInt8}, Ptr{Float64}, Ptr{UInt16}, Cuint, Ptr{UInt8}),
          sig, st, ek, hm, logn, zeros(UInt8, 48n))
    Int.(sig)
end

println("# cref_sign_kat.jl -- GENERATED by scripts/gen_cref_sign_kat.jl.  Do not edit.")
println("#")
println("# The C reference implementation's own signing output, recorded so that")
println("# test_falcon.jl can assert byte-for-byte reproduction (docs/debug_log.md #050).")
println("# Each entry: (f, g, F, G, salt, prng_state, hashed_point, s2, compressed_bytes).")
println("const CREF_SIGN_KAT = [")
for trial in 1:8
    logn = 9; n = 512
    r = chacha20(shake256(codeunits("cref-sign-kat/key/$trial"), 56))
    sk, _ = falcon_keygen(n, k -> randombytes!(r, k))
    ek = c_expand(sk.f, sk.g, sk.F, sk.G, logn)
    salt = shake256(codeunits("cref-sign-kat/salt/$trial"), 40)
    msg  = collect(codeunits("cref sign kat message $trial"))
    pt = hash_to_point(msg, salt, n; q = FALCON_512.q)
    st = shake256(codeunits("cref-sign-kat/prng/$trial"), 56)
    s2 = c_sign(st, ek, UInt16.(pt), logn)
    buf = zeros(UInt8, FALCON_512.sig_bytes)
    len = ccall((:shim_comp_encode, SHIM), Csize_t,
                (Ptr{UInt8}, Csize_t, Ptr{Int16}, Cuint),
                buf, FALCON_512.sig_bytes - 41, Int16.(s2), logn)
    println("  (")
    println("    ", sk.f, ",")
    println("    ", sk.g, ",")
    println("    ", sk.F, ",")
    println("    ", sk.G, ",")
    println("    ", collect(salt), ",")
    println("    ", collect(st), ",")
    println("    ", Int.(pt), ",")
    println("    ", s2, ",")
    println("    ", buf[1:Int(len)], ",")
    println("  ),")
end
println("]")
