using Test
using Random
using Falcon

# --- small helpers shared by the test files ---------------------------------

"Trial division primality test; only used on q, so speed is irrelevant."
function isprime_trial(n::Integer)
    n < 2 && return false
    n % 2 == 0 && return n == 2
    d = 3
    while d * d <= n
        n % d == 0 && return false
        d += 2
    end
    return true
end

"Evaluate a polynomial at a complex point by Horner, for property checks."
function _evalpoly_c(f::AbstractVector, z::Complex)
    acc = zero(z)
    for c in reverse(f)
        acc = acc * z + ComplexF64(c)
    end
    return acc
end

"""
Largest absolute difference between two equal-length numeric vectors.

Used everywhere in test_fft.jl: floating-point comparisons need a number, and
`isapprox` on vectors hides *which* entry drifted when it fails.
"""
function _maxabsdiff(a::AbstractVector, b::AbstractVector)
    length(a) == length(b) ||
        throw(DimensionMismatch("lengths $(length(a)) and $(length(b))"))
    isempty(a) && return 0.0
    return maximum(abs(a[i] - b[i]) for i in eachindex(a))
end

"Evaluate a polynomial at `x` modulo `m` by Horner."
function _evalpoly_mod(f::AbstractVector{<:Integer}, x::Integer, m::Integer)
    acc = 0
    for c in reverse(f)
        acc = mod(acc * Int(x) + Int(c), m)
    end
    return acc
end

# --- golden vectors ---------------------------------------------------------
#
# Included once, here, rather than from the individual test files: several
# modules legitimately want the same vectors (test_ntt.jl cross-checks against
# poly.jl's), and including a file that defines `const`s twice is a warning at
# best.  Generated by scripts/gen_vectors.py; see falcon/README.md.

include(joinpath(@__DIR__, "vectors", "shake256_kat.jl"))
include(joinpath(@__DIR__, "vectors", "chacha20_kat.jl"))
include(joinpath(@__DIR__, "vectors", "poly_kat.jl"))
include(joinpath(@__DIR__, "vectors", "ntt_kat.jl"))
include(joinpath(@__DIR__, "vectors", "fft_kat.jl"))
include(joinpath(@__DIR__, "vectors", "fft_c_kat.jl"))
include(joinpath(@__DIR__, "vectors", "fft_roots_c_kat.jl"))
include(joinpath(@__DIR__, "vectors", "ntrugen_kat.jl"))
include(joinpath(@__DIR__, "vectors", "samplerz_kat.jl"))
include(joinpath(@__DIR__, "vectors", "keygen_kat.jl"))
include(joinpath(@__DIR__, "vectors", "ffsampling_kat.jl"))
include(joinpath(@__DIR__, "vectors", "encoding_kat.jl"))
include(joinpath(@__DIR__, "vectors", "cref_kat.jl"))
include(joinpath(@__DIR__, "vectors", "cref_sign_kat.jl"))
include(joinpath(@__DIR__, "vectors", "falcon_kat.jl"))

@testset "Falcon.jl" begin
    include("test_params.jl")   # module 1
    include("test_shake.jl")    # module 2
    include("test_poly.jl")     # module 3
    include("test_ntt.jl")      # module 4
    include("test_fft.jl")      # module 5
    include("test_ntrugen.jl")  # module 6
    include("test_samplerz.jl") # module 7
    include("test_keygen.jl")   # module 6 + 7: key generation
    include("test_ffsampling.jl") # module 8
    include("test_encoding.jl")  # module 9
    include("test_falcon.jl")    # module 10
    include("test_spec.jl")      # the specification's own tables (#046)

    # The other parameter set, end to end.  Kept last and in its own file
    # because it is by far the slowest thing in the suite: one n = 1024 key
    # generation dominates it (docs/debug_log.md #032).  Set the environment
    # variable FALCON_SKIP_1024=1 to leave it out during quick iteration -- but
    # it must run before anything is committed.
    if get(ENV, "FALCON_SKIP_1024", "0") == "1"
        @info "skipping test_falcon1024.jl (FALCON_SKIP_1024=1)"
    else
        include("test_falcon1024.jl")
    end
end
