using Test
using Falcon

# --- small helpers shared by the test files ---------------------------------

"Trial division primality test; only used on q, so speed is irrelevant."
function isprime_trial(n::Integer)
    n < 2 && return false
    n % 2 == 0 && return n == 2
    d = 3
    while d * d <= n
        n % d == 0 && return false
        d += 2
    end
    return true
end

"Evaluate a polynomial at a complex point by Horner, for property checks."
function _evalpoly_c(f::AbstractVector, z::Complex)
    acc = zero(z)
    for c in reverse(f)
        acc = acc * z + ComplexF64(c)
    end
    return acc
end

"Evaluate a polynomial at `x` modulo `m` by Horner."
function _evalpoly_mod(f::AbstractVector{<:Integer}, x::Integer, m::Integer)
    acc = 0
    for c in reverse(f)
        acc = mod(acc * Int(x) + Int(c), m)
    end
    return acc
end

# --- golden vectors ---------------------------------------------------------
#
# Included once, here, rather than from the individual test files: several
# modules legitimately want the same vectors (test_ntt.jl cross-checks against
# poly.jl's), and including a file that defines `const`s twice is a warning at
# best.  Generated by scripts/gen_vectors.py; see falcon/README.md.

include(joinpath(@__DIR__, "vectors", "shake256_kat.jl"))
include(joinpath(@__DIR__, "vectors", "chacha20_kat.jl"))
include(joinpath(@__DIR__, "vectors", "poly_kat.jl"))
include(joinpath(@__DIR__, "vectors", "ntt_kat.jl"))

@testset "Falcon.jl" begin
    include("test_params.jl")   # module 1
    include("test_shake.jl")    # module 2
    include("test_poly.jl")     # module 3
    include("test_ntt.jl")      # module 4
end
